apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-eunu
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0070-tenant/tkrw-pr712-0075-0070-app/devfile-sample-eunu@sha256:013cc3bdbf27d04d3ee44e246f796a8bedf8e2cc26d699e6276abc23d1a9691e
        name: my-nodejs
        resources: {}
status: {}
